#!/bin/sh

set -e
export LC_ALL=C

help() {
  echo 'Usage:  cargo suckless is a work in progress'
}
echo() {
  printf '%s\n' "$*"
}

if [ "$1" != suckless ]; then
  help
  exit 1
fi
shift

if [ "$1" = --help ]; then
  help
  exit
fi

export CARGO_HOME="${CARGO_HOME:-${HOME}/.cargo}"

help
